# Utility

# git
[[plugins]]
repo = 'mattn/gist-vim'
depends = 'webapi-vim'
on_cmd = ['Gist']

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'gregsexton/gitv'
depends = 'vim-fugitive'
on_cmd = ['Gitv']

# Undo
[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']
hook_post_source = 'nnoremap <Leader>g :GundoToggle<CR>'

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = ['nxo', '<Plug>(quickrun)']
hook_post_source = '''
    nmap <Leader>r <Plug>(quickrun)
    let g:quickrun_config = {
        \ "*": {"runner": "remote/vimproc"},
        \ }
'''

# python

# need pip install jedi
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3', 'djangohtml']
hook_post_source = '''
    " jediにvimの設定を任せると'completeopt+=preview'するので
    " 自動設定機能をOFFにし手動で設定を行う
    let g:jedi#auto_vim_configuration = 0
    " 補完の最初の項目が選択された状態だと使いにくいためオフにする
    let g:jedi#popup_select_first = 0
    " quickrunと被るため大文字に変更
    let g:jedi#rename_command = '<Leader>R'
    " gundoと被るため大文字に変更 (2013-06-24 10:00 追記）
    let g:jedi#goto_assignments_command = '<Leader>G'
'''
# django
[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'python3', 'djangohtml']

# virtualenv
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', 'python3', 'djangohtml']
