
# tap repositories and their packages

tap homebrew/core
brew arpack
brew aspcud
brew autoconf
brew automake
brew bat
brew binutils
brew boost
brew cairo
brew camlp4
brew carthage
brew clang-format
brew clingo
brew cmake
brew cocoapods
brew cpanminus
brew darcs
brew docker
brew dpkg
brew eigen
brew epstool
brew ffmpeg
brew fftw
brew fig2dev
brew flac
brew fltk
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghostscript
brew gibo
brew git
brew gl2ps
brew glib
brew glpk
brew gmp
brew gnu-tar
brew gnuplot
brew gnutls
brew go
brew gobject-introspection
brew gpatch
brew graphicsmagick
brew graphite2
brew harfbuzz
brew haskell-stack
brew hdf5
brew hub
brew icarus-verilog
brew icu4c
brew ideviceinstaller
brew ilmbase
brew imagemagick
brew imagemagick@6
brew ios-deploy
brew isl
brew jasper
brew jemalloc
brew jpeg
brew lame
brew libcroco
brew libevent
brew libffi
brew libidn2
brew libimobiledevice
brew libmpc
brew libogg
brew libplist
brew libpng
brew librsvg
brew libsndfile
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvorbis
brew libvpx
brew libvterm
brew libxml2
brew libyaml
brew libzip
brew little-cms2
brew lua
brew luajit
brew mas
brew mercurial
brew metis
brew mpfr
brew msgpack
brew ncurses
brew neovim
brew netpbm
brew nettle
brew ninja
brew node
brew nodebrew
brew ocaml
brew ocamlbuild
brew octave
brew opam
brew open-mpi
brew openblas
brew openexr
brew openjpeg
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew perl
brew pixman
brew pkg-config
brew plotutils
brew portaudio
brew potrace
brew pstoedit
brew python
brew python@2
brew qhull
brew qrupdate
brew rbenv
brew readline
brew reattach-to-user-namespace
brew rlwrap
brew ruby
brew ruby-build
brew screenfetch
brew sdl2
brew snappy
brew sqlite
brew suite-sparse
brew sundials
brew swiftlint
brew szip
brew tbb
brew texinfo
brew tfenv
brew theora
brew tig
brew tmux
brew tnftp
brew unibilium
brew veclibfort
brew webp
brew wget
brew x264
brew x265
brew xvid
brew xz
brew yarn --without-node
brew zsh

tap homebrew/cask
cask blender
cask crunch
cask dotnet
cask keycast
cask mactex-no-gui
cask paraview
cask processing
cask touchdesigner
cask wireshark
cask xquartz

tap beeftornado/rmtree

tap d12frosted/emacs-plus
brew emacs-plus

tap ibdecodable/tap
brew iblinter

tap kylef/formulae
brew swiftenv

tap lvillani/tap

tap mono0926/license-plist
brew license-plist

tap mscharley/homebrew
brew alacritty

tap neovim/neovim

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --with-powerline

# Other Homebrew packages
brew openssl
brew usbmuxd

# Other Cask applications
cask brackets
cask docker
cask filezilla
cask kitematic
cask openscad
cask pliim
cask skim
cask virtualbox
cask xmind
cask zotero

# App Store applications
appstore 824171161 Affinity Designer (1.6.1)
appstore 824183456 Affinity Photo (1.6.7)
appstore 672206759 Disk Diag (1.4)
appstore 549083868 Display Menu (2.2.3)
appstore 406056744 Evernote (7.8)
appstore 682658836 GarageBand (10.3.2)
appstore 668208984 GIPHY CAPTURE (4.1)
appstore 408981434 iMovie (10.1.10)
appstore 409183694 Keynote (8.3)
appstore 411213048 LadioCast (000013000)
appstore 539883307 LINE (5.12.1)
appstore 518830108 Memory Cleaner (3.0.1)
appstore 409203825 Numbers (5.3)
appstore 823766827 OneDrive (18.214.1021)
appstore 409201541 Pages (7.3)
appstore 803453959 Slack (3.3.7)
appstore 497799835 Xcode (10.1)
