
# tap repositories and their packages

tap argon/mas
brew mas

tap beeftornado/rmtree

tap caskroom/cask
cask fastlane
cask virtualbox
cask vagrant
cask mactex
cask xquartz
cask filezilla

tap caskroom/fonts
cask font-source-code-pro

tap caskroom/versions

tap codefirst/sparkling
brew brew-sparkling

tap homebrew/boneyard

tap homebrew/core
brew arpack
brew aspcud
brew atk
brew autoconf
brew automake
brew bazel
brew bdw-gc
brew binutils
brew bison
brew cabal-install
brew cairo
brew camlp4
brew camlp5
brew carthage
brew clasp
brew cloog
brew cmake
brew coq
brew coreutils
brew curl
brew czmq
brew epstool
brew erlang
brew fftw
brew fltk
brew fontconfig
brew fontforge
brew freetype
brew gawk
brew gcc
brew gcc@4.9
brew gd
brew gdb
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghc
brew ghi
brew ghostscript
brew gibo
brew gifsicle
brew git
brew git-flow
brew gl2ps
brew glib
brew glpk
brew gmp
brew gmp@4
brew gnu-sed
brew gnuplot --with-qt@5.7 --with-x11
brew gnutls
brew go
brew gobject-introspection
brew graphicsmagick
brew graphite2
brew graphviz
brew gringo
brew gsettings-desktop-schemas
brew gtk+
brew gtk+3
brew gtk-mac-integration
brew guile
brew harfbuzz
brew haskell-stack
brew hdf5
brew hicolor-icon-theme
brew hiredis
brew http-parser
brew hub
brew icarus-verilog
brew icu4c
brew imagemagick
brew intltool
brew ipcalc
brew iperf
brew isl
brew isl@0.11
brew isl@0.12
brew jpeg
brew jruby
brew kotlin
brew lame
brew libcroco
brew libepoxy
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libmpc
brew libmpc@0.8
brew libogg
brew libpng
brew librsvg
brew libsodium
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libvorbis
brew libyaml
brew little-cms2
brew lua
brew lzip
brew mad
brew mecab
brew mecab-ipadic
brew mercurial
brew metis
brew mobiledevice
brew mpfr
brew mpfr@2
brew mysql
brew nettle
brew ninja
brew nmap
brew node
brew nodebrew
brew numpy
brew ocaml
brew ocamlbuild
brew octave
brew opam
brew openssl
brew openssl@1.1
brew p11-kit
brew pango
brew pcre
brew peco
brew perl
brew perl-build
brew pixman
brew pkg-config
brew plenv
brew plotutils
brew portmidi
brew pstoedit
brew py2cairo
brew pyenv
brew pyenv-virtualenv
brew pygobject
brew pygtk
brew pyqt
brew python
brew python3
brew qhull
brew qrupdate
brew qscintilla2
brew qt
brew qt@5.7
brew r
brew rbenv
brew readline
brew reattach-to-user-namespace
brew redis
brew rlwrap
brew ruby
brew ruby-build
brew sdl
brew sdl2
brew sdl_image
brew sdl_mixer
brew sdl_ttf
brew shared-mime-info
brew sip --with-python3
brew sl
brew smpeg
brew sox
brew sqlite
brew suite-sparse
brew swi-prolog
brew swiftgen
brew swiftlint
brew swig
brew szip
brew tbb
brew texinfo
brew tig
brew tree
brew unixodbc
brew utf8proc
brew veclibfort
brew vim --with-python3 --with-lua
brew vimpager
brew webp
brew weechat --with-perl --with-ruby --with-python
brew wget
brew wxmac
brew wxpython
brew xz
brew zeromq
brew zsh --without-etcdir

tap homebrew/gui

tap homebrew/head-only

tap homebrew/headonly

tap homebrew/python

tap homebrew/science

tap homebrew/versions

tap kylef/formulae
brew swiftenv

tap mono0926/license-plist
brew license-plist

tap peco/peco
brew migemogrep

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --vim-powerline

# Other Homebrew packages
brew npm
brew transfig

# App Store applications
appstore 824171161 Affinity Designer (1.5.5)
appstore 824183456 Affinity Photo (1.5.2)
appstore 405843582 Alfred (1.2)
appstore 703369642 Audio Converter Lite (2.0.6)
appstore 672206759 Disk Diag (1.4)
appstore 549083868 Display Menu (2.2.2)
appstore 682658836 GarageBand (10.2.0)
appstore 408981434 iMovie (10.1.6)
appstore 408981381 iPhoto (9.6.1)
appstore 409183694 Keynote (7.2)
appstore 896624060 Kobito (2.3.8)
appstore 411213048 LadioCast (000012002)
appstore 518830108 Memory Cleaner X (2.0.5)
appstore 409203825 Numbers (4.2)
appstore 409201541 Pages (6.2)
appstore 425955336 Skitch (2.8)
appstore 803453959 Slack (2.6.2)
appstore 425424353 The Unarchiver (3.11.1)
appstore 497799835 Xcode (8.3.3)
