
# tap repositories and their packages

tap argon/mas
brew mas

tap caskroom/cask
cask coqide
cask emacs
cask filezilla
cask mactex
cask xquartz

tap caskroom/fonts
cask font-source-code-pro

tap caskroom/versions

tap codefirst/sparkling
brew brew-sparkling

tap homebrew/boneyard

tap homebrew/core
brew aspcud
brew atk
brew autoconf
brew automake
brew bdw-gc
brew binutils
brew boost
brew boost-python
brew cabal-install
brew cairo
brew camlp4
brew camlp5
brew carthage
brew clasp
brew cloog
brew cmake
brew coq
brew coreutils
brew curl
brew czmq
brew emacs --with-cocoa
brew epstool
brew erlang
brew fftw
brew fltk
brew fontconfig
brew fontforge
brew freetype
brew gcc
brew gd
brew gdb
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghc
brew ghi
brew ghostscript
brew gibo
brew gifsicle
brew git
brew git-flow
brew gl2ps
brew glib
brew gmp
brew gnuplot --with-x11
brew gnutls
brew go
brew gobject-introspection
brew graphicsmagick
brew graphviz
brew gringo
brew gsettings-desktop-schemas
brew gtk+
brew gtk+3
brew gtk-mac-integration
brew guile
brew harfbuzz
brew haskell-stack
brew hicolor-icon-theme
brew hiredis
brew http-parser
brew hub
brew icarus-verilog
brew icu4c
brew imagemagick
brew intltool
brew iperf
brew isl
brew jpeg
brew jruby
brew kotlin
brew lame
brew libcroco
brew libepoxy
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libmpc
brew libpng
brew librsvg
brew libsodium
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libyaml
brew little-cms2
brew lua
brew mad
brew mercurial
brew mobiledevice
brew mpfr
brew mysql
brew nettle
brew ninja
brew nmap
brew node --with-full-icu
brew nodebrew
brew numpy
brew ocaml
brew ocamlbuild
brew opam
brew openssl
brew pango
brew pcre
brew peco
brew perl
brew perl-build
brew pixman
brew pkg-config
brew plenv
brew plotutils
brew portmidi
brew pstoedit
brew py2cairo
brew pyenv
brew pyenv-virtualenv
brew pygobject
brew pygtk
brew python
brew python3
brew qscintilla2
brew rbenv
brew readline
brew reattach-to-user-namespace
brew redis
brew rlwrap
brew ruby
brew ruby-build
brew sdl
brew sdl2
brew sdl_image
brew sdl_mixer
brew sdl_ttf
brew shared-mime-info
brew sip
brew sl
brew smpeg
brew sox
brew sqlite
brew swi-prolog
brew swiftgen
brew swiftlint
brew swig
brew szip
brew tbb
brew tig
brew tree
brew unixodbc
brew utf8proc
brew vim --with-python3
brew vimpager
brew webp
brew weechat --with-ruby --with-python --with-perl
brew wget
brew wxmac
brew wxpython
brew xz
brew zeromq
brew zsh --without-etcdir

tap homebrew/gui

tap homebrew/head-only

tap homebrew/headonly

tap homebrew/python

tap homebrew/science
brew arpack
brew glpk
brew hdf5
brew metis
brew octave
brew qhull
brew qrupdate
brew r
brew suite-sparse
brew transfig
brew veclibfort

tap homebrew/versions

tap kylef/formulae
brew swiftenv

tap mono0926/license-plist
brew license-plist

tap peco/peco
brew migemogrep

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --vim-powerline

# Other Homebrew packages
brew cloog018
brew gcc49
brew gmp4
brew gtkwave
brew isl011
brew libmpc08
brew mpfr2
brew pyenv-pip-rehash
brew pyqt5
brew qt5
brew vpython

# App Store applications
appstore 824171161 Affinity Designer (1.5.1)
appstore 824183456 Affinity Photo (1.4.3)
appstore 405843582 Alfred (1.2)
appstore 703369642 Audio Converter Lite (2.0.5)
appstore 672206759 Disk Diag (1.4)
appstore 682658836 GarageBand (10.1.3)
appstore 939343785 Icon Set Creator (1.1.4)
appstore 409183694 Keynote (7.0.5)
appstore 896624060 Kobito (2.3.8)
appstore 539883307 LINE (4.10.2)
appstore 411213048 LadioCast (000012000)
appstore 409203825 Numbers (4.0.5)
appstore 409201541 Pages (6.0.5)
appstore 803453959 Slack (2.3.1)
appstore 425424353 The Unarchiver (3.11.1)
appstore 497799835 Xcode (8.1)
appstore 408981434 iMovie (10.1.3)
appstore 408981381 iPhoto (9.6.1)
