
# tap repositories and their packages

tap homebrew/core
brew aspcud
brew atk
brew autoconf
brew automake
brew bazel
brew bdw-gc
brew binutils
brew bison
brew cabal-install
brew cairo
brew camlp4
brew carthage
brew cloog
brew cmake
brew coreutils
brew cscope
brew curl
brew czmq
brew docker
brew flac
brew fontconfig
brew fontforge
brew freetype
brew gawk
brew gcc
brew gcc@4.9
brew gd
brew gdb
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghc
brew ghc@8.0
brew ghi
brew ghostscript
brew gibo
brew gifsicle
brew git
brew git-flow
brew glib
brew glide
brew gmp
brew gmp@4
brew gnu-sed
brew go
brew gobject-introspection
brew graphite2
brew graphviz
brew gsettings-desktop-schemas
brew gtk+
brew gtk+3
brew gtk-mac-integration
brew guile
brew harfbuzz
brew haskell-stack
brew hicolor-icon-theme
brew hiredis
brew http-parser
brew hub
brew icarus-verilog
brew icu4c
brew imagemagick
brew intltool
brew ipcalc
brew iperf
brew isl
brew isl@0.11
brew isl@0.12
brew jpeg
brew jruby
brew kotlin
brew lame
brew lapack
brew libcroco
brew libepoxy
brew libevent
brew libffi
brew libgpg-error
brew libmpc
brew libmpc@0.8
brew libogg
brew libpng
brew librsvg
brew libsndfile
brew libsodium
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libvorbis
brew libyaml
brew little-cms2
brew llvm --with-toolchain
brew lua
brew lzip
brew mad
brew mas
brew mecab
brew mecab-ipadic
brew mercurial
brew metis
brew mobiledevice
brew mpfr
brew mpfr@2
brew mysql
brew nettle
brew ninja
brew nmap
brew node
brew nodebrew
brew numpy
brew ocaml
brew ocamlbuild
brew opam
brew openblas
brew openssl
brew openssl@1.1
brew p11-kit
brew pango
brew pcre
brew peco
brew perl
brew perl-build
brew pixman
brew pkg-config
brew plenv
brew plotutils
brew portmidi
brew py2cairo
brew pyenv
brew pyenv-virtualenv
brew pygobject
brew pygtk
brew pyqt
brew python
brew python3
brew qscintilla2
brew qt
brew qt@5.7
brew r
brew rbenv
brew readline
brew reattach-to-user-namespace
brew redis
brew rename
brew rlwrap
brew ruby
brew ruby-build
brew rust
brew sdl
brew sdl2
brew sdl_image
brew sdl_mixer
brew sdl_ttf
brew shared-mime-info
brew sip
brew sl
brew smpeg
brew sox
brew sphinx-doc
brew sqlite
brew swi-prolog
brew swiftgen
brew swiftlint
brew swig
brew szip
brew tbb
brew telnet
brew texinfo
brew tig
brew tree
brew unixodbc
brew utf8proc
brew veclibfort
brew vim
brew vimpager
brew webp
brew wget
brew wxmac
brew wxpython
brew xz
brew zeromq
brew zsh --without-etcdir

tap homebrew/boneyard

tap homebrew/gui

tap homebrew/head-only

tap homebrew/headonly

tap homebrew/python

tap homebrew/science

tap homebrew/versions

tap caskroom/cask
cask fastlane
cask virtualbox
cask docker
cask vagrant
cask mactex
cask xquartz
cask filezilla

tap caskroom/fonts
cask font-source-code-pro

tap caskroom/versions

tap argon/mas

tap beeftornado/rmtree

tap codefirst/sparkling
brew brew-sparkling

tap kylef/formulae
brew swiftenv

tap mono0926/license-plist
brew license-plist

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --vim-powerline

# Other Homebrew packages
brew clasp
brew gringo

# App Store applications
appstore 405843582 Alfred (1.2)
appstore 672206759 Disk Diag (1.4)
appstore 549083868 Display Menu (2.2.2)
appstore 682658836 GarageBand (10.2.0)
appstore 668208984 GIPHY CAPTURE (3.7)
appstore 408981434 iMovie (10.1.8)
appstore 408981381 iPhoto (9.6.1)
appstore 409183694 Keynote (7.3)
appstore 411213048 LadioCast (000012003)
appstore 518830108 Memory Cleaner (2.5)
appstore 409203825 Numbers (4.3)
appstore 409201541 Pages (6.3)
appstore 425955336 Skitch (2.8)
appstore 803453959 Slack (2.8.2)
appstore 425424353 The Unarchiver (3.11.3)
appstore 1278508951 Trello (2.10.0)
appstore 497799835 Xcode (9.1)
